#------------------------------------------------------------------------
#                         LoneWolves-Core
#                          lonewolves.net
#                      lonewolves.net/discord
#                   Coded by EzJamo and DeathRealms
#------------------------------------------------------------------------

#Server Options
#Disables all spawner placement (use after spawner place date)
enable-spawner-placement: true

#Sets the chat format, supports placeholders.
chat-format:
  enabled: true
  format: '&8[[FACTION]&8] %luckperms_prefix%%player_nickname%%deluxetags_tag%&7: &r%message%'

#Disables strength 2 potions
disable-strength-2: true

#Disables placing blocks on top of the nether
disable-top-of-nether-place: true

#Disables placing skeleton spawners in the nether
disable-skeleton-spawners-nether: true

#Disables the depth strider enchantment on boots
disable-depth-strider: true

#Disables weather on the server.
disable-weather: true

#Changes the default join and quit messages. Set to "none" to disable them.
#Use "%player_name%" to get the players name.
join-message: 'none'
quit-message: 'none'

#This is the name of the server as defined in your bungeecord config that you want the /hub command to take you to.
hub-server: 'hub'

#If enabled then each warp will have its own permission like this "lw.warp.<WarpName>"
per-warp-permissions: false

#The amount of time it takes for a player to teleport to a warp in seconds.
warp-delay: 4

#The amount of time it takes for a player to teleport to spawn in seconds.
spawn-delay: 4

#Name of the essentials kit new players receive when they first join
first-join-kit: 'member'

Messages:
  ActionBarMessage: '&aYou are invisible to other players!'
  welcome-message: '&fWelcome &4%player_name% &fto &lLone&4&lWolves&f! &4#%server_unique_joins%'

#/help command
#To add another page copy the format below and replace "1" with the page number.
Help:
  1:
    - '&7&m----------------------------------------------------'
    - '&6&lServer Help &8- &f(1/2)'
    - '&7&m----------------------------------------------------'
    - '&e/f help &8- &7View the help page for Factions.'
    - '&e/tpa &8- &7Request to teleport to a player.'
    - '&e/warp &8- &7View all the available warps.'
    - '&e/shop &8- &7Use this to Buy or Sell your items.'
    - '&e/sell &8- &7Use this to Sell your items.'
    - '&e/kits &8- &7View all of the kits, and right click for a preview.'
    - '&e/ah &8- &7View items players have put up for sale, or list your own.'
    - '&e/distance &8- &7See how many blocks out you are from spawn.'
    - '&e/links &8- &7Shows you useful links for the server.'
    - '&e/lottery help &8- &7View the help page for the Lottery'
    - '&7&m--------------------&6/help 2&7&m--------------------------'
  
  2:
    - '&7&m----------------------------------------------------'
    - '&6&lServer Help &8- &f(2/2)'
    - '&7&m----------------------------------------------------'
    - '&e/trade &f<playername> &8- &7Trade items with another player.'
    - '&e/rules &8- &7View all of the server rules.'
    - '&e/preview &f<kit> &8- &7Shows you a preview of the specified kit.'
    - '&e/nv &8- &7Enable/Disable the night vision effect.'
    - '&e/ping &f<playername> &8- &7View your own or another players ping.'
    - '&e/stats &f<playername> &8- &7View your own or another players stats.'
    - '&e/auc &8- &7Start a live auction for players to bid on.'
    - '&7&m--------------------&6Last Page&7&m------------------------'

#/rules command
#To add another page copy the format below and replace "1" with the page number.
Rules:
  1:
    - '&7&m----------------------------------------------------'
    - '&c&lServer Rules &8- &f(1/2)'
    - '&7&m----------------------------------------------------'
    - '&c[1] &7No advertising.'
    - '&c[2] &7No spamming.'
    - '&c[3] &7No disrespecting players or staff.'
    - '&c[4] &7No death remarks/threats.'
    - '&c[5] &7No racism.'
    - '&c[6] &7No inapproriate nicknames or links.'
    - '&c[7] &7No abusing helpop.'
    - '&c[8] &7No impersonating players or staff.'
    - '&c[9] &7No hacking.'
    - '&c[10] &7No exploiting glitches.'
    - '&7&m--------------------&c/rules 2&7&m-------------------------'

  2:
    - '&7&m----------------------------------------------------'
    - '&c&lServer Rules &8- &f(2/2)'
    - '&7&m----------------------------------------------------'
    - '&c[11] &7No bypassing a mute or ban.'
    - '&c[12] &7No DDoS/Dox threats.'
    - '&c[13] &7No harassing players.'
    - '&c[14] &7No charging back.'
    - '&c[15] &7No combat logging.'
    - '&c[16] &7No "bitch claiming".'
    - '&c[17] &7No voting on alts.'
    - '&c[18] &7No general toxicity towards players or staff.'
    - '&c[19] &7No more than 10 accounts on your IP.'
    - '&7&m--------------------&cLast Page&7&m------------------------'
  
#/links command
Links:
  - '&3&lForums: &ahttps://lonewolves.net'
  - '&3&lStore: &ahttp://store.lonewolves.net'
  - '&3&lDiscord: &ahttps://lonewolves.net/discord'
  - '&3&lBans: &ahttps://lonewolves.net/bans'
  
#Custom Command Messages
#To give players permission for these commands they need the permission "lw.customcmd.<command>"
Custom Commands:
  example: #This will be the the command
    - '&6I''m an example custom command' #This is the message it will send the player. You can also do multiple lines.
  forums:
    - '&3&lForums: &ahttps://lonewolves.net'
  store:
    - '&3&lStore: &ahttp://store.lonewolves.net'
  bans:
    - '&3&lBans: &ahttps://lonewolves.net/bans'

#/nv command.
NightVision:
  Enabled: '&aYou have enabled your night vision effects.'
  Disabled: '&cYou have disabled your night vision effects.'

#/Ping command
Ping:
  Self: '&fPing: %player_ping%'
  Others: '&f%player_name%''s ping is %player_ping%'
  
#/playtime command
Playtime:
  - '&4%player_name%''s &fplaytime is &4%playtime%'
  
#/stats command
Stats:
  - '&4&m--------&8[&f%player_name%&8]&4&m--------'
  - '      &aKills: &e%kills%'
  - '      &aDeaths: &e%deaths%'
  - '      &aVotes: &e%superbvote_votes%'
  - '      &aPlaytime: &e%playtime%'
  - '&4&m--------------------------'

#Scoreboard messages.
Scoreboard:
  Title: '&f&lLone&4&lWolves'
  Default:
    - '&7&m-----------------'
    - '&dOnline: &f%supervanish_playercount%'
    - '&dBalance: &f%vault_eco_balance_formatted%'
    - ''
    - '&aFaction: &r%faction%'
    - ''
    - '&cKills: &f%statistic_player_kills%'
    - '&cDeaths: &f%statistic_deaths%'
  Koth:
    - ''
    - '&dKOTH: &f%koth%'
    - '&dX: &f%x%'
    - '&dZ: &f%z%'
    - '&dTime: &f%time%'

#/worth command
Worth:
  1:
    - '&4&m--------&8[&2Faction Top Worth&8]&4&m--------'
    - '&aCave Spider Spawner &8- &e$5,000'
    - '&aSpider Spawner &8- &e$15,000'
    - '&aZombie Spawner &8- &e$15,000'
    - '&aSkeleton Spawner &8- &e$15,000'
    - '&aBlaze Spawner &8- &e$18,000'
    - '&aCreeper Spawner &8- &e$35,000'
    - '&aIron Golem Spawner &8- &e$50,000'
    - '&4&m------------&2/worth 2&4&m-------------'

  2:
    - '&4&m--------&8[&2Faction Top Worth&8]&4&m--------'
    - '&aCoal Block &8- &e$25'
    - '&aRedstone Block &8- &e$40'
    - '&aIron Block &8- &e$60'
    - '&aHopper &8- &e$75'
    - '&aGold Block &8- &e$90'
    - '&aDiamond Block &8- &e$200'
    - '&aEmerald Block &8- &e$500'
    - '&aBeacon &8- &e$3000'
    - '&4&m--------------------------------'
  
#/commands messages
Commands:
  helper:
    - '&7&m----------------------------------------------------'
    - '&d&lHelper Commands'
    - '&7&m----------------------------------------------------'
    - '&d/invsee &f<playername>'
    - '&d/checkmute &f<playername>'
    - '&d/clearchat'
    - '&d/mute'
    - '&d/ipmute'
    - '&d/kick'
    - '&d/mutechat'
    - '&d/tempmute'
    - '&d/unmute'
    - '&d/warn'
    - '&d/unwarn'
    - '&d/warnings'
    - '&d/history'
    - '&d/punish'
    - '&d/sc'
    - '&d/sct'
    - '&7&m--------------------&dLast Page&7&m-----------------------'
  mod:
    - '&7&m----------------------------------------------------'
    - '&9&lMod Commands'
    - '&7&m----------------------------------------------------'
    - '&9/checkban &f<playername>'
    - '&9/alts &f<playername>'
    - '&9/co i'
    - '&9/afk'
    - '&9/fly'
    - '&9/god'
    - '&9/socialspy'
    - '&9/tp'
    - '&9/tphere'
    - '&9/tpo'
    - '&9/tpohere'
    - '&9/ban'
    - '&9/tempban'
    - '&9/banip'
    - '&9/banlist'
    - '&9/unban'
    - '&9/mod'
    - '&9/freeze'
    - '&9/inv'
    - '&9/v'
    - '&7&m--------------------&9Last Page&7&m-----------------------'
  vip:
    - '&7&m----------------------------------------------------'
    - '&e&lVIP Commands'
    - '&7&m----------------------------------------------------'
    - '&e/kit vip'
    - '&e/back'
    - '&e/near'
    - '&e/feed'
    - '&e/sethome &f(4 homes)'
    - '&e/pv 1'
    - '&7&m--------------------&eLast Page&7&m-----------------------'
  vip+:
    - '&7&m----------------------------------------------------'
    - '&b&lVIP+ Commands'
    - '&7&m----------------------------------------------------'
    - '&bAll commands from previous rank.'
    - '&b/kit vip+'
    - '&b/kit vip'
    - '&b/hat'
    - '&b/nick'
    - '&b/sethome &f(6 homes)'
    - '&7&m--------------------&bLast Page&7&m-----------------------'
  mvp:
    - '&7&m----------------------------------------------------'
    - '&c&lMVP Commands'
    - '&7&m----------------------------------------------------'
    - '&cAll commands from previous rank.'
    - '&c/kit mvp'
    - '&c/kit vip+'
    - '&c/trash'
    - '&c/craft'
    - '&c/sethome &f(8 homes)'
    - '&7&m--------------------&cLast Page&7&m-----------------------'
  noble:
    - '&7&m----------------------------------------------------'
    - '&3&lNoble Commands'
    - '&7&m----------------------------------------------------'
    - '&3All commands from previous rank.'
    - '&3/kit noble'
    - '&3/kit mvp'
    - '&3/heal'
    - '&3/sethome &f(12 homes)'
    - '&3/pv 2'
    - '&7&m--------------------&3Last Page&7&m-----------------------'
  mystic:
    - '&7&m----------------------------------------------------'
    - '&5&lMystic Commands'
    - '&7&m----------------------------------------------------'
    - '&5All commands from previous rank.'
    - '&5/kit mystic'
    - '&5/kit noble'
    - '&5/echest'
    - '&5/sethome &f(16 homes)'
    - '&7&m--------------------&5Last Page&7&m-----------------------'
  kingpin:
    - '&7&m----------------------------------------------------'
    - '&2&lKingpin Commands'
    - '&7&m----------------------------------------------------'
    - '&2All commands from previous rank.'
    - '&2/kit kingpin'
    - '&2/kit mystic'
    - '&2/nick &f(%RainbowColor_with colors%&f)'
    - '&2/sethome &f(22 homes)'
    - '&2/pv 3'
    - '&7&m--------------------&2Last Page&7&m-----------------------'

#All blocks with an inventory or any blocks that when right clicked shouldn't equip armor.
#This shouldn't have to be messed with.
blocked:
    - FURNACE
    - CHEST
    - TRAPPED_CHEST
    - BEACON
    - DISPENSER
    - DROPPER
    - HOPPER
    - WORKBENCH
    - ENCHANTMENT_TABLE
    - ENDER_CHEST
    - ANVIL
    - BED_BLOCK
    - FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - ACACIA_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - IRON_DOOR_BLOCK
    - WOODEN_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - WOOD_BUTTON
    - STONE_BUTTON
    - TRAP_DOOR
    - IRON_TRAPDOOR
    - DIODE_BLOCK_OFF
    - DIODE_BLOCK_ON
    - REDSTONE_COMPARATOR_OFF
    - REDSTONE_COMPARATOR_ON
    - FENCE
    - SPRUCE_FENCE
    - BIRCH_FENCE
    - JUNGLE_FENCE
    - DARK_OAK_FENCE
    - ACACIA_FENCE
    - NETHER_FENCE
    - BREWING_STAND
    - CAULDRON
    - SIGN_POST
    - WALL_SIGN
    - SIGN
    - LEVER
