name: LW-Core
main: me.ezjamo.Lonewolves
author: EzJamo & DeathRealms
description: Multipurpose essentials plugin coded by the LoneWolves Development Team.
softdepend: [PlaceholderAPI, Essentials, KoTH]
depend: [Vault]
version: 2.8

commands:
  request:
    aliases:
      - helpop
  mod:
    aliases:
      - h
      - staff
  sc:
    aliases:
      - staffchat
  acc:
    aliases:
      - adminchat
  distance:
   aliases: [dist]
  links:
   aliases: [link, forums] 
  help:
  lw:
  rules:
  setslots:
  setspawn:
  spawn:
   aliases: [espawn]
  freeze:
  nv:
  hub:
  admin:
  removemm:
  commands:
   aliases: [cmds]
  inv:
  ping:
  startkoth:
  kits:
   aliases: [kit]
  preview:
  stats:
  demote:
  playtime:
   aliases: [pt]
  worth:
  scoreboard:
    aliases:
      - fb
      - sb
   
permissions:
  lw.helpop:
    description: Helpop/request.
    default: op
  lw.mod:
    description: 'Toggle mod mode.'
    default: op
  lw.color:
    description: 'Chat color.'
    default: op
  lw.helpopr:
    description: 'Helpop receive.'
    default: op
  lw.staffchat:
    description: 'Chat for staff.'
  lw.slots:
    description: 'Set server slots.'
  lw.nv:
    description: 'Gives nightvision.'
  lw.switchinv:
    description: 'Switches between a blank inventory and your previous one.'
  lw.koth:
    description: 'Opens a GUI to start a koth.'
  lw.kits:
    description: 'Opens a kits GUI.'
  lw.preview:
    description: 'Shows a preview of the selected kit.'
  lw.demote:
    description: 'Demotes the specified user.'
  lw.fly.bypass:
    description: 'Lets user bypass fly disable in other faction claims.'